# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cnc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cnc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcnc.proto\"B\n\x0bReadRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08node_id2\x18\x02 \x01(\t\x12\x10\n\x08node_id3\x18\x03 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05value\x18\x01 \x01(\t\".\n\x0cWriteRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32i\n\nCNCService\x12+\n\x0cReadVariable\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12.\n\rWriteVariable\x12\r.WriteRequest\x1a\x0e.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cnc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=13
  _globals['_READREQUEST']._serialized_end=79
  _globals['_READRESPONSE']._serialized_start=81
  _globals['_READRESPONSE']._serialized_end=110
  _globals['_WRITEREQUEST']._serialized_start=112
  _globals['_WRITEREQUEST']._serialized_end=158
  _globals['_WRITERESPONSE']._serialized_start=160
  _globals['_WRITERESPONSE']._serialized_end=192
  _globals['_CNCSERVICE']._serialized_start=194
  _globals['_CNCSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)