# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gRPCCom.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gRPCCom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgRPCCom.proto\"\x14\n\x12IsConnectedRequest\"\"\n\x10IsConnectedReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\r\n\x0bReadRequest\"<\n\tReadFinal\x12\x1d\n\x07request\x18\x01 \x01(\x0b\x32\x0c.ReadRequest\x12\x10\n\x08selector\x18\x02 \x01(\x05\"\'\n\tReadReply\x12\x1a\n\x06values\x18\x01 \x03(\x0b\x32\n.DataValue\"t\n\x0cWriteRequest\x12)\n\x06values\x18\x01 \x03(\x0b\x32\x19.WriteRequest.ValuesEntry\x1a\x39\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.DataValue:\x02\x38\x01\"?\n\tDataValue\x12\x13\n\tint_value\x18\x01 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x02 \x01(\x02H\x00\x42\x06\n\x04kind\"\x1c\n\nWriteReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\"\n\x10\x41\x63quisitionReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\"1\n\x0f\x41\x63quisitionData\x12\x1e\n\x06values\x18\x01 \x03(\x0b\x32\x0e.SingleAcqData\"m\n\rSingleAcqData\x12\x13\n\x0bsource_name\x18\x01 \x01(\t\x12\x12\n\nvalue_name\x18\x02 \x01(\t\x12\x13\n\tint_value\x18\x03 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x01H\x00\x42\x07\n\x05value2\xc1\x02\n\nCLMService\x12\x35\n\x0bIsConnected\x12\x13.IsConnectedRequest\x1a\x11.IsConnectedReply\x12&\n\nReadHeader\x12\x0c.ReadRequest\x1a\n.ReadReply\x12$\n\x08ReadData\x12\x0c.ReadRequest\x1a\n.ReadReply\x12\x1e\n\x04Read\x12\n.ReadFinal\x1a\n.ReadReply\x12#\n\x05Write\x12\r.WriteRequest\x1a\x0b.WriteReply\x12\x36\n\x0fSendAcquisition\x12\x10.AcquisitionData\x1a\x11.AcquisitionReply\x12\x31\n\x0fReadAcquisition\x12\x0c.ReadRequest\x1a\x10.AcquisitionDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPCCom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEREQUEST_VALUESENTRY']._loaded_options = None
  _globals['_WRITEREQUEST_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_ISCONNECTEDREQUEST']._serialized_start=17
  _globals['_ISCONNECTEDREQUEST']._serialized_end=37
  _globals['_ISCONNECTEDREPLY']._serialized_start=39
  _globals['_ISCONNECTEDREPLY']._serialized_end=73
  _globals['_READREQUEST']._serialized_start=75
  _globals['_READREQUEST']._serialized_end=88
  _globals['_READFINAL']._serialized_start=90
  _globals['_READFINAL']._serialized_end=150
  _globals['_READREPLY']._serialized_start=152
  _globals['_READREPLY']._serialized_end=191
  _globals['_WRITEREQUEST']._serialized_start=193
  _globals['_WRITEREQUEST']._serialized_end=309
  _globals['_WRITEREQUEST_VALUESENTRY']._serialized_start=252
  _globals['_WRITEREQUEST_VALUESENTRY']._serialized_end=309
  _globals['_DATAVALUE']._serialized_start=311
  _globals['_DATAVALUE']._serialized_end=374
  _globals['_WRITEREPLY']._serialized_start=376
  _globals['_WRITEREPLY']._serialized_end=404
  _globals['_ACQUISITIONREPLY']._serialized_start=406
  _globals['_ACQUISITIONREPLY']._serialized_end=440
  _globals['_ACQUISITIONDATA']._serialized_start=442
  _globals['_ACQUISITIONDATA']._serialized_end=491
  _globals['_SINGLEACQDATA']._serialized_start=493
  _globals['_SINGLEACQDATA']._serialized_end=602
  _globals['_CLMSERVICE']._serialized_start=605
  _globals['_CLMSERVICE']._serialized_end=926
# @@protoc_insertion_point(module_scope)
